<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

use Mezzio\Authentication\DefaultUserFactory;
use Mezzio\Authentication\UserInterface;
use Mezzio\Authentication\AuthenticationMiddleware;
use Mezzio\Authentication\AuthenticationMiddlewareFactory;

return [
    'dependencies' => [
        'factories' => [
            App\Handler\JWTHandler::class => App\Handler\JWTHandlerFactory::class,
            App\Middleware\Authorization\JWTMiddleware::class => App\Middleware\Authorization\JWTMiddlewareFactory::class,
//            App\Middleware\Authorization\LoginMiddleware::class => App\Middleware\Authorization\LoginMiddlewareFactory::class,
            Mezzio\Session\SessionMiddleware::class => Mezzio\Session\SessionMiddlewareFactory::class,
            UserInterface::class => DefaultUserFactory::class,
            AuthenticationMiddleware::class => AuthenticationMiddlewareFactory::class,
        ],
    ],
];
